# -*- coding: utf-8 -*-
"""python Assignmnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFkcTGfwqJ8GdLTw3wVsadWPxEpVSa6J
"""

abhishek